run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-dirs:
    - bin
    - vendor
    - docs
  
  exclude-rules:
    # deferでのClose()のエラーチェックは除外
    - text: "Error return value of `(.*\\.)?Close` is not checked"
      linters:
        - errcheck
    
    # deferでのRollback()は無視
    - text: "Error return value of `(.*\\.)?Rollback` is not checked"
      linters:
        - errcheck
    
    # テストファイルでのエラーチェック漏れは許容
    - path: _test\.go
      linters:
        - errcheck
        - ineffassign
  
  max-issues-per-linter: 0
  max-same-issues: 0
