# .github/actions/setup-go/action.yml
name: 'Composite Go Setup'
description: 'Checks out code, sets up Go, caches modules, and installs dependencies'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'backend/go.mod'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('backend/go.mod') }}-${{ hashFiles('backend/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles('backend/go.mod') }}-
          ${{ runner.os }}-go-

    - name: Install dependencies
      shell: bash
      working-directory: ./backend
      run: go mod download
